# Generated by Django 3.0.7 on 2020-06-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tickets', models.DecimalField(decimal_places=2, max_digits=4)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Movie')),
            ],
        ),
    ]
