# Generated by Django 3.0.7 on 2020-06-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
